import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/website/Header";
import Footer from "@/components/website/Footer";
import StoreProvider from "@/redux/StoreProvider";
import { getprofile } from "@/utils/api";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let user = null;
  const response = await getprofile()
  if (response.success) {
    user = response.data
  }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col bg-[#f5f1ed]`}>
        <StoreProvider>
          <Header user={user} />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
